name: Deploy to SFTP

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to SFTP
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Remove excluded files
        run: |
          rm -rf .git .github node_modules cypress tests docs .env.example README.md package.json package-lock.json vitest.config.js || true

      - name: SFTP Deploy
        uses: wangyucode/sftp-upload-action@v2.0.2
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: ${{ secrets.SFTP_PORT }}
          localDir: '.'
          remoteDir: ${{ secrets.SFTP_TARGET_DIR }}
